### ISSUE TITLE
Inconsistency in Factory parameter setting

### ISSUE THREAD

**Issue by arthurmloureiro** [LSSTDESC/firecrown#481]
**Describe the bug**
It seems like setting some parameters in the factory like `alphag` will actually fix those parameters inside firecrown instead of simply instantiating the factory objects with those values. This can will an issue for CosmoAPI as it will create a discrepancy between factory parameters for synthetic analysis. 

For example, at the moment we can set the parameters for a synthetic analysis in CosmoAPI with
```yaml
    systematics:
      type: WeakLensingFactory
      per_bin_systematics:
      - type: MultiplicativeShearBiasFactory
        mult_bias: [1e-3, 1e-3, 1e-3, 1e-3, 1e-3]
      - type: PhotoZShiftFactory
        delta_z: &delta_z [0.2, 0.1, 0.1, 0.2, 0.1]
      global_systematics:
      - type: LinearAlignmentSystematicFactory
        alphag: 1.0
```
This allows the user to set the parameters to generate a fake SACC data file. 
However, if the user recycles this part of the code to then run a likelihood analysis, `alphag` will be fixed while the other parameters are not.

This is not really a bug just something that can cause some issues as different systematic factories seem to have different behaviour when constructing them.
